//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope.ITMS.Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegineUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegineUser(string uid, string pwd, string agent_code, string co_name, string link_man, string mob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserInfo(string uid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUserPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EditUserPwd(string uid, string pwd, string newpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMessages(string uid, string pwd, string tos, string msg, string otime);
        
        // CODEGEN: 参数“Bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFax", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hope.ITMS.Web.ServiceReference1.SendFaxResponse SendFax(Hope.ITMS.Web.ServiceReference1.SendFaxRequest request);
        
        // CODEGEN: 参数“Bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hope.ITMS.Web.ServiceReference1.SendMMSResponse SendMMS(Hope.ITMS.Web.ServiceReference1.SendMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewSendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NewSendMMS(string uid, string pwd, string tos, string title, Hope.ITMS.Web.ServiceReference1.MMSContent[] mmsContentList, string otime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS_Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMMS_Test(string uid, string pwd, string mobno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMsTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMMsTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMessageInfo(string snum);
        
        // CODEGEN: 参数“FileBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hope.ITMS.Web.ServiceReference1.SendVoiceResponse SendVoice(Hope.ITMS.Web.ServiceReference1.SendVoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFaxRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFaxRecord(string uid, string pwd, string num, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVoiceRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVoiceRecord(string uid, string pwd, string num, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMessageRecord(string uid, string pwd, string num, string StartDate, string EndDate, string isday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_SMS_MO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GET_SMS_MO(string uid, string pwd, string IDtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MSP_MO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GET_MSP_MO(string uid, string pwd, string IDtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TelCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TelCall(string uid, string pwd, string host_call, string caller);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFax", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFaxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string faxno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string men;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Bytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string FileName;
        
        public SendFaxRequest() {
        }
        
        public SendFaxRequest(string uid, string pwd, string faxno, string men, string title, byte[] Bytes, string FileName) {
            this.uid = uid;
            this.pwd = pwd;
            this.faxno = faxno;
            this.men = men;
            this.title = title;
            this.Bytes = Bytes;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFaxResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFaxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendFaxResult;
        
        public SendFaxResponse() {
        }
        
        public SendFaxResponse(string SendFaxResult) {
            this.SendFaxResult = SendFaxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mobno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Bytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string mmsFileName;
        
        public SendMMSRequest() {
        }
        
        public SendMMSRequest(string uid, string pwd, string mobno, string title, string content, byte[] Bytes, string mmsFileName) {
            this.uid = uid;
            this.pwd = pwd;
            this.mobno = mobno;
            this.title = title;
            this.content = content;
            this.Bytes = Bytes;
            this.mmsFileName = mmsFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendMMSResult;
        
        public SendMMSResponse() {
        }
        
        public SendMMSResponse(string SendMMSResult) {
            this.SendMMSResult = SendMMSResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MMSContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] musicByteField;
        
        private string musicTypeField;
        
        private byte[] imgByteField;
        
        private string textField;
        
        private string imgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] MusicByte {
            get {
                return this.musicByteField;
            }
            set {
                this.musicByteField = value;
                this.RaisePropertyChanged("MusicByte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MusicType {
            get {
                return this.musicTypeField;
            }
            set {
                this.musicTypeField = value;
                this.RaisePropertyChanged("MusicType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] ImgByte {
            get {
                return this.imgByteField;
            }
            set {
                this.imgByteField = value;
                this.RaisePropertyChanged("ImgByte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImgType {
            get {
                return this.imgTypeField;
            }
            set {
                this.imgTypeField = value;
                this.RaisePropertyChanged("ImgType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendVoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendVoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string vto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string vtxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string svrno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string str_time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string end_time;
        
        public SendVoiceRequest() {
        }
        
        public SendVoiceRequest(string uid, string pwd, string vto, string vtxt, string mode, byte[] FileBytes, string svrno, string str_time, string end_time) {
            this.uid = uid;
            this.pwd = pwd;
            this.vto = vto;
            this.vtxt = vtxt;
            this.mode = mode;
            this.FileBytes = FileBytes;
            this.svrno = svrno;
            this.str_time = str_time;
            this.end_time = end_time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendVoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendVoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendVoiceResult;
        
        public SendVoiceResponse() {
        }
        
        public SendVoiceResponse(string SendVoiceResult) {
            this.SendVoiceResult = SendVoiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Hope.ITMS.Web.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Hope.ITMS.Web.ServiceReference1.Service1Soap>, Hope.ITMS.Web.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegineUser(string uid, string pwd, string agent_code, string co_name, string link_man, string mob) {
            return base.Channel.RegineUser(uid, pwd, agent_code, co_name, link_man, mob);
        }
        
        public string GetUserInfo(string uid, string pwd) {
            return base.Channel.GetUserInfo(uid, pwd);
        }
        
        public string EditUserPwd(string uid, string pwd, string newpwd) {
            return base.Channel.EditUserPwd(uid, pwd, newpwd);
        }
        
        public string SendMessages(string uid, string pwd, string tos, string msg, string otime) {
            return base.Channel.SendMessages(uid, pwd, tos, msg, otime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hope.ITMS.Web.ServiceReference1.SendFaxResponse Hope.ITMS.Web.ServiceReference1.Service1Soap.SendFax(Hope.ITMS.Web.ServiceReference1.SendFaxRequest request) {
            return base.Channel.SendFax(request);
        }
        
        public string SendFax(string uid, string pwd, string faxno, string men, string title, byte[] Bytes, string FileName) {
            Hope.ITMS.Web.ServiceReference1.SendFaxRequest inValue = new Hope.ITMS.Web.ServiceReference1.SendFaxRequest();
            inValue.uid = uid;
            inValue.pwd = pwd;
            inValue.faxno = faxno;
            inValue.men = men;
            inValue.title = title;
            inValue.Bytes = Bytes;
            inValue.FileName = FileName;
            Hope.ITMS.Web.ServiceReference1.SendFaxResponse retVal = ((Hope.ITMS.Web.ServiceReference1.Service1Soap)(this)).SendFax(inValue);
            return retVal.SendFaxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hope.ITMS.Web.ServiceReference1.SendMMSResponse Hope.ITMS.Web.ServiceReference1.Service1Soap.SendMMS(Hope.ITMS.Web.ServiceReference1.SendMMSRequest request) {
            return base.Channel.SendMMS(request);
        }
        
        public string SendMMS(string uid, string pwd, string mobno, string title, string content, byte[] Bytes, string mmsFileName) {
            Hope.ITMS.Web.ServiceReference1.SendMMSRequest inValue = new Hope.ITMS.Web.ServiceReference1.SendMMSRequest();
            inValue.uid = uid;
            inValue.pwd = pwd;
            inValue.mobno = mobno;
            inValue.title = title;
            inValue.content = content;
            inValue.Bytes = Bytes;
            inValue.mmsFileName = mmsFileName;
            Hope.ITMS.Web.ServiceReference1.SendMMSResponse retVal = ((Hope.ITMS.Web.ServiceReference1.Service1Soap)(this)).SendMMS(inValue);
            return retVal.SendMMSResult;
        }
        
        public string NewSendMMS(string uid, string pwd, string tos, string title, Hope.ITMS.Web.ServiceReference1.MMSContent[] mmsContentList, string otime) {
            return base.Channel.NewSendMMS(uid, pwd, tos, title, mmsContentList, otime);
        }
        
        public string SendMMS_Test(string uid, string pwd, string mobno) {
            return base.Channel.SendMMS_Test(uid, pwd, mobno);
        }
        
        public string SendMMsTest() {
            return base.Channel.SendMMsTest();
        }
        
        public string GetMessageInfo(string snum) {
            return base.Channel.GetMessageInfo(snum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hope.ITMS.Web.ServiceReference1.SendVoiceResponse Hope.ITMS.Web.ServiceReference1.Service1Soap.SendVoice(Hope.ITMS.Web.ServiceReference1.SendVoiceRequest request) {
            return base.Channel.SendVoice(request);
        }
        
        public string SendVoice(string uid, string pwd, string vto, string vtxt, string mode, byte[] FileBytes, string svrno, string str_time, string end_time) {
            Hope.ITMS.Web.ServiceReference1.SendVoiceRequest inValue = new Hope.ITMS.Web.ServiceReference1.SendVoiceRequest();
            inValue.uid = uid;
            inValue.pwd = pwd;
            inValue.vto = vto;
            inValue.vtxt = vtxt;
            inValue.mode = mode;
            inValue.FileBytes = FileBytes;
            inValue.svrno = svrno;
            inValue.str_time = str_time;
            inValue.end_time = end_time;
            Hope.ITMS.Web.ServiceReference1.SendVoiceResponse retVal = ((Hope.ITMS.Web.ServiceReference1.Service1Soap)(this)).SendVoice(inValue);
            return retVal.SendVoiceResult;
        }
        
        public string GetFaxRecord(string uid, string pwd, string num, string StartDate, string EndDate) {
            return base.Channel.GetFaxRecord(uid, pwd, num, StartDate, EndDate);
        }
        
        public string GetVoiceRecord(string uid, string pwd, string num, string StartDate, string EndDate) {
            return base.Channel.GetVoiceRecord(uid, pwd, num, StartDate, EndDate);
        }
        
        public string GetMessageRecord(string uid, string pwd, string num, string StartDate, string EndDate, string isday) {
            return base.Channel.GetMessageRecord(uid, pwd, num, StartDate, EndDate, isday);
        }
        
        public string GET_SMS_MO(string uid, string pwd, string IDtype) {
            return base.Channel.GET_SMS_MO(uid, pwd, IDtype);
        }
        
        public string GET_MSP_MO(string uid, string pwd, string IDtype) {
            return base.Channel.GET_MSP_MO(uid, pwd, IDtype);
        }
        
        public string TelCall(string uid, string pwd, string host_call, string caller) {
            return base.Channel.TelCall(uid, pwd, host_call, caller);
        }
    }
}
